import Footer from './component/layout/Footer'
import Header from './component/layout/Header'
import './globals.css'


export const metadata = {
  title: 'SDU | Software Development Unit',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
